-- CreateTable
CREATE TABLE `Batik` (
    `BATIKID` CHAR(5) NOT NULL,
    `BATIKNAME` VARCHAR(50) NOT NULL,
    `BATIKDESC` VARCHAR(200) NOT NULL,
    `BATIKIMG` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`BATIKID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Likes` (
    `USERID` CHAR(16) NOT NULL,
    `POSTID` CHAR(16) NOT NULL,

    PRIMARY KEY (`USERID`, `POSTID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Post` (
    `POSTID` CHAR(16) NOT NULL,
    `USERID` CHAR(16) NOT NULL,
    `BATIKID` CHAR(5) NOT NULL,
    `POSTIMG` VARCHAR(255) NOT NULL,
    `CAPTION` VARCHAR(250) NULL,
    `LIKES` INTEGER NOT NULL,
    `CREATEDAT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `UPDATEDAT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`POSTID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `USERID` CHAR(16) NOT NULL,
    `USERNAME` VARCHAR(25) NOT NULL,
    `EMAIL` VARCHAR(200) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `PROFILEIMG` VARCHAR(255) NULL,
    `CREATEDAT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `UPDATEDAT` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `User_EMAIL_key`(`EMAIL`),
    PRIMARY KEY (`USERID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Likes` ADD CONSTRAINT `Likes_USERID_fkey` FOREIGN KEY (`USERID`) REFERENCES `User`(`USERID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `Likes` ADD CONSTRAINT `Likes_POSTID_fkey` FOREIGN KEY (`POSTID`) REFERENCES `Post`(`POSTID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `Post` ADD CONSTRAINT `Post_USERID_fkey` FOREIGN KEY (`USERID`) REFERENCES `User`(`USERID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `Post` ADD CONSTRAINT `Post_BATIKID_fkey` FOREIGN KEY (`BATIKID`) REFERENCES `Batik`(`BATIKID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
